MPC.add_entry_to_playlist: Don't attempt to remove missing files
This happened to me and I'm not sure why.  The logs look like this::

    INFO:teamplayer: Station 1: Adding DJ Ango's “Hello I Love You” by Oleander
    DEBUG:teamplayer: copying to 1-db0070468b98e642.mp3
    ERROR:teamplayer: 1-db0070468b98e642.mp3 never made it to the playlist
    Exception in thread Station 1:
    Traceback (most recent call last):
      File "/usr/lib64/python3.4/threading.py", line 920, in _bootstrap_inner
        self.run()
      File "/opt/teamplayer/lib/python3.4/site-packages/teamplayer/lib/async.py", line 130, in run
        self.mpc.add_entry_to_playlist(entry)
      File "/opt/teamplayer/lib/python3.4/site-packages/teamplayer/lib/mpc.py", line 197, in add_entry_to_playlist
        os.unlink(filename)
    FileNotFoundError: [Errno 2] No such file or directory: '1-db0070468b98e642.mp3'

This change checks to see if the file exists before calling unlink().  In the
future we'll have to investigate why the file disappeared.